language: python
python:
  - "2.7"

env:
  - DJANGO=1.6

# Starting xvfb (X Virtual Framebuffer)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - git clone git://github.com/maxmind/geoip-api-c
  - cd geoip-api-c
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r ./requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - python ./manage.py test --settings=codeweekeu.settings_travis --cov web --cov api --cov-report term-missing -v
after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
