language: python
python:
  - "2.7"

env:
  - DJANGO=1.6

# Starting xvfb (X Virtual Framebuffer)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r codeweekeu/reqs.txt

# command to run tests, e.g. python setup.py test
script:  python codeweekeu/manage.py test api
 --settings=codeweekeu.settings

notifications:
  email:
    on_success: change
    on_failure: change
